---
- name: Build Core Switch Config and Upload to device
  hosts: all
  gather_facts: yes
  roles:
   - CoreSwitch

  tasks:
  - name: Upload Configuration
#    delegate_to: all
    arubaos_cx_ssh_cli:
      ip: "{{ ansible_host }}"
      user: admin
      password: Aruba123
      # Commands as a list
      commands: ["copy tftp://192.168.56.110/{{ hostname }}.cfg running-config vrf mgmt"]

  - name: Output the last 10 config errors
    arubaos_cx_ssh_cli:
      ip: 192.168.56.108
      user: admin
      password: aruba123
      commands: ["show events -r -d hpe-config | begin 10 192.168.56.110"]
    register: events
  - debug:
      msg: "{{events.cli_output.0.split('\n')}}"
